name: alc_book
description: ALC Book flutter app

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.12+92

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  google_fonts: ^5.1.0
  page_transition: ^2.0.9
  shared_preferences: ^2.0.15
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.4
  url_launcher: ^6.1.7
  flutter_cached_pdfview: ^0.4.2
  cached_network_image: ^3.2.3
  material_floating_search_bar_2: ^0.5.0
#  syncfusion_flutter_pdfviewer: ^22.2.11
  flutter_native_splash: ^2.2.16
  recaptcha_enterprise_flutter: ^18.4.0 #to fix recaptcha warning in play console
  new_version_plus: ^0.0.11
  flutter_screenutil: ^5.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter_native_splash:
  image: assets/icon/icon.png
  color: "#ffffff"
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
