name: alc_book
description: ALC Book flutter app

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  page_transition: ^2.0.5
  shared_preferences: ^2.0.12


  firebase_core: ^1.12.0
  firebase_storage: ^10.2.6
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.6

  url_launcher: ^6.0.18

  flutter_cached_pdfview: ^0.4.1
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
