name: alc_book
description: ALC Book flutter app

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  page_transition: ^2.0.9
  shared_preferences: ^2.0.15


  firebase_core: ^2.0.0
  firebase_storage: ^11.0.1
  cloud_firestore: ^4.0.1
  firebase_auth: ^4.0.1

  url_launcher: ^6.1.6

  flutter_cached_pdfview: ^0.4.1
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
