class Images {
  static String splash = 'assets/images/splash.svg';
  static String book1 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F1.jpg?alt=media';
  static String book2 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F2.jpg?alt=media';
  static String book3 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F3.jpg?alt=media';
  static String book4 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F4.jpg?alt=media';
  static String book5 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F5.jpg?alt=media';
  static String book6 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F6.jpg?alt=media';
  static String book7 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F7.jpg?alt=media';
  static String book8 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F8.jpg?alt=media';
  static String book9 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F9.jpg?alt=media';
  static String book10 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F10.jpg?alt=media';
  static String book11 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F11.jpg?alt=media';
  static String book12 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F12.jpg?alt=media';
  static String book13 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F13.jpg?alt=media';
  static String book14 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F14.jpg?alt=media';
  static String book15 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F15.jpg?alt=media';
  static String book16 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F16.jpg?alt=media';
  static String book17 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F17.jpg?alt=media';
  static String book18 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F18.jpg?alt=media';
  static String book19 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F19.jpg?alt=media';
  static String book20 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F20.jpg?alt=media';
  static String book21 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F21.jpg?alt=media';
  static String book22 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F22.jpg?alt=media';
  static String book23 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F23.jpg?alt=media';
  static String book24 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F24.jpg?alt=media';
  static String book25 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F25.jpg?alt=media';
  static String book26 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F26.jpg?alt=media';
  static String book27 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F27.jpg?alt=media';
  static String book28 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2FChristian-who-love-god-first.jpg?alt=media';
  static String book29 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2F28.jpg?alt=media';
  static String book30 =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/covers%2FkingShip.jpg?alt=media';
  static String profile =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/profile.png?alt=media';
  static String about =
      'https://firebasestorage.googleapis.com/v0/b/timothy-books.appspot.com/o/about.jpg?alt=media';
}
